import '../globals.css'
import { ThemeProvider } from '../providers'
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/ui/resizable"
import { Sidebar } from '@/components/sidebar'
// import UserContext from "@/app/UserContext";
import { useState } from 'react'
import { createClient } from '@/utils/supabase/server'
import UserContext from '../UserContext'


export const metadata = {
  title: 'User Management',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const supabase = createClient();
  const { data, error } = await supabase.auth.getUser()

  if (error) {
    console.log("error", error);
  }

  if (data) {
    console.log("data", data);
  }


  return (
    <>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >

        <div className="flex h-full justify-center p-6">
          <div className="container">
            {children}
          </div>
        </div>
      </ThemeProvider >
    </>
  )
}
