import '../globals.css'
import { ThemeProvider } from '../providers'
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/ui/resizable"
import { Sidebar } from '@/components/sidebar'
// import UserContext from "@/app/UserContext";
import { useState } from 'react'
import { createClient } from '@/utils/supabase/server'
import UserContext from '../UserContext'
import Footer from '@/components/footer'
import HeaderNav from '@/components/header'


export const metadata = {
  title: 'User Management',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const supabase = createClient();
  const { data, error } = await supabase.auth.getUser()

  // if (error) {
  //   console.log("error", error);
  // }

  return (
    <>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >

        <div className="">
          <div className="flex flex-col">
            <div className="flex-grow">
              <div className="container mx-auto p-0 max-w-7xl bg-background">

                <HeaderNav />

                <div className="px-6">
                  {children}
                  {/* <Footer /> */}
                </div>
              </div>
            </div>
          </div>
        </div>
      </ThemeProvider >
    </>
  )
}
