export const MockRatingsSample = {
    "results": [
        {
            "title": {
                "property_name": "The Golden Nugget",
                "rating_number": 72,
                "rating_category": "Satisfactory",
                "feedback": {
                    "summary": "The title 'The Golden Nugget' effectively conveys a sense of value but lacks specific details that can attract potential guests. Consider making adjustments to enhance clarity and appeal.",
                    "items": [
                        {
                            "title": "Memorable Name",
                            "feedback": "The name is catchy and easy to remember, which is a plus for attracting guests."
                        },
                        {
                            "title": "Needs More Detail",
                            "feedback": "While the title is appealing, it doesn’t highlight the unique features or benefits of the property."
                        },
                        {
                            "title": "Potential for Improvement",
                            "feedback": "Adding descriptive keywords or amenities in the title could enhance its attractiveness."
                        },
                        {
                            "title": "Geographic Feature",
                            "feedback": "Emphasizing the central location could attract more guests looking for convenience."
                        },
                        {
                            "title": "Unique Selling Point",
                            "feedback": "Consider incorporating features like the pool or tranquility in the title."
                        }
                    ]
                },
                "suggestions": [
                    "Incorporate the mention of the pool in the title for emphasis.",
                    "Highlight the central location in the title to attract professionals.",
                    "Consider adding descriptors like 'Cozy' or 'Serene'.",
                    "Include a target audience tag, such as 'Ideal for Business Travelers'.",
                    "Mention a unique feature or benefit in the title."
                ],
                "expert_ratings": [
                    54,
                    61,
                    75,
                    65,
                    68,
                    41,
                    58,
                    82,
                    43,
                    60,
                    69,
                    79,
                    74,
                    73,
                    59,
                    55,
                    57,
                    52,
                    66,
                    50,
                    48,
                    77,
                    49,
                    56,
                    33,
                    47,
                    71,
                    39,
                    30,
                    32,
                    67,
                    78,
                    82,
                    72,
                    64,
                    38,
                    34,
                    66,
                    86,
                    88,
                    85,
                    63,
                    91,
                    90,
                    82,
                    29,
                    93,
                    99,
                    94,
                    40,
                    31,
                    46,
                    45,
                    44,
                    36,
                    22,
                    18,
                    23,
                    20,
                    19,
                    24,
                    28,
                    26,
                    25,
                    27,
                    12,
                    11,
                    14,
                    8,
                    9,
                    7,
                    3,
                    17,
                    5,
                    6,
                    76,
                    15,
                    1,
                    16,
                    65,
                    11,
                    35,
                    10,
                    4,
                    89,
                    2,
                    95,
                    96,
                    97,
                    98,
                    84,
                    87
                ],
                "title_rewrites": [
                    "The Golden Nugget: A Central Yuma Oasis with Pool",
                    "The Golden Nugget: Peaceful Retreat and Key Location",
                    "The Golden Nugget: Comfort and Convenience in Yuma"
                ],
                "revisions": null
            },
            "description": {
                "property_name": "The Golden Nugget",
                "rating_number": 69,
                "rating_category": "Needs Work",
                "feedback": {
                    "summary": "Your property description effectively outlines the key features and amenities available. However, it could benefit from a more engaging tone and additional details to draw potential guests in.",
                    "items": [
                        {
                            "title": "Engagement",
                            "feedback": "Try to incorporate a more inviting tone to entice potential guests. Highlight unique aspects that set your property apart."
                        },
                        {
                            "title": "Location Details",
                            "feedback": "Add more context about nearby attractions or activities in Yuma to enhance the appeal of the location."
                        },
                        {
                            "title": "Clarity in Guest Access",
                            "feedback": "Clarify how shared spaces work with other guests for better transparency."
                        },
                        {
                            "title": "Highlight Unique Features",
                            "feedback": "Focus on the pool and outdoor spaces to attract guests looking for relaxation."
                        },
                        {
                            "title": "Professional Appeal",
                            "feedback": "Since you're targeting traveling professionals, consider mentioning Wi-Fi speed or workspace setups in more detail."
                        }
                    ]
                },
                "suggestions": [
                    "Enhance the description with a warm and inviting tone.",
                    "Include nearby attractions and local hotspots to attract guests.",
                    "Clarify the arrangement of shared spaces for transparency.",
                    "Emphasize amenities like the year-round pool and backyard activities.",
                    "Mention details about workspace for traveling professionals."
                ],
                "expert_ratings": [
                    21,
                    87,
                    39,
                    41,
                    53,
                    22,
                    34,
                    25,
                    56,
                    76,
                    79,
                    73,
                    68,
                    64,
                    55,
                    67,
                    48,
                    85,
                    66,
                    79,
                    54,
                    33,
                    61,
                    59,
                    74,
                    57,
                    82,
                    42,
                    70,
                    35,
                    36,
                    75,
                    49,
                    82,
                    44,
                    69,
                    52,
                    46,
                    78,
                    61,
                    29,
                    62,
                    87,
                    45,
                    51,
                    50,
                    54,
                    67,
                    29,
                    88,
                    91,
                    38,
                    81,
                    66,
                    60,
                    77,
                    26,
                    45,
                    80,
                    29,
                    37,
                    55,
                    85,
                    33,
                    70,
                    84,
                    27,
                    62,
                    83,
                    59,
                    42,
                    54,
                    78,
                    71,
                    25,
                    36,
                    29,
                    60,
                    87,
                    73,
                    49,
                    39,
                    32,
                    23,
                    88,
                    61,
                    45,
                    91,
                    62,
                    67,
                    72,
                    82,
                    20,
                    76,
                    36,
                    87,
                    63,
                    68,
                    84,
                    21,
                    30,
                    33,
                    88,
                    78,
                    42,
                    59,
                    53,
                    66,
                    61,
                    72,
                    22
                ],
                "description_rewrite": {
                    "listing_description": "Keep it simple at The Golden Nugget, a peaceful escape located in the center of Yuma, AZ. Ideal for traveling professionals, this home is equipped with all you need for a comfortable stay. Enjoy the inviting pool year-round and nearby walking paths perfect for morning runs or leisurely strolls. Your convenient base is just minutes from key destinations like YRMC and MCAS.",
                    "your_property": "The Golden Nugget offers a spacious living area, fully equipped kitchen, and a peaceful ambiance perfect for your stay in Yuma.",
                    "guest_access": "Guests can access a full kitchen, living room, dining room, and large backyard with a refreshing pool. Please note that common areas are shared with other guests.",
                    "interaction_with_guests": "I am available to assist you during your stay and help make your experience memorable. Don’t hesitate to reach out with any questions!",
                    "other_details_to_note": "The Golden Nugget is ideal for long-term stays, offering convenient amenities for business travelers. Self check-in is available for your convenience."
                },
                "revisions": null
            },
            "amenities": {
                "property_name": "Standard Stay Listing",
                "rating_number": 73,
                "rating_category": "Satisfactory",
                "feedback": {
                    "summary": "Your listing offers a comprehensive set of amenities that cater to a wide range of guest needs. Many appreciated the attention to comfort and convenience, though there are some areas that could be enhanced for even better guest experience.",
                    "items": [
                        {
                            "title": "Comfortable Sleeping Arrangements",
                            "feedback": "Guests noted the quality of the bed linens and the availability of extra pillows and blankets, making for a comfortable sleeping environment."
                        },
                        {
                            "title": "Exceptional Outdoor Facilities",
                            "feedback": "The outdoor shower and BBQ grill were highlights for many guests, providing a fantastic outdoor experience."
                        },
                        {
                            "title": "Complete Kitchen Setup",
                            "feedback": "Reviewers were pleased with the kitchen amenities, particularly the coffee maker and dishwasher, which added to their convenience during the stay."
                        }
                    ]
                },
                "suggestions": [
                    "Consider providing more entertainment options, such as streaming services or board games to enhance guest engagement.",
                    "Evaluate the pricing for long-term stays to attract more guests looking for extended vacations or work retreats.",
                    "Enhance the outdoor space with seating or lighting options to create a more inviting ambiance for evening gatherings."
                ],
                "expert_ratings": [
                    52,
                    63,
                    55,
                    74,
                    82,
                    61,
                    79,
                    88,
                    70,
                    76,
                    58,
                    67,
                    49,
                    91,
                    93,
                    85,
                    53,
                    72,
                    48,
                    62,
                    56,
                    77,
                    76,
                    73,
                    84,
                    67,
                    78,
                    69,
                    68,
                    60,
                    64,
                    81,
                    51,
                    54,
                    55,
                    80,
                    63,
                    70,
                    49,
                    75,
                    59,
                    65,
                    32,
                    33,
                    45,
                    72,
                    82,
                    61,
                    79,
                    88,
                    55,
                    78,
                    76,
                    61,
                    86,
                    68,
                    54,
                    57,
                    73,
                    60,
                    71,
                    82,
                    89,
                    65,
                    45,
                    38,
                    87,
                    42,
                    33,
                    50,
                    68,
                    66,
                    62,
                    64,
                    61,
                    70,
                    51,
                    49,
                    64,
                    53,
                    50,
                    60,
                    63,
                    82,
                    74,
                    90,
                    31,
                    30,
                    85,
                    77,
                    87,
                    53,
                    69,
                    62,
                    49,
                    65,
                    47,
                    52,
                    59,
                    72,
                    74,
                    83,
                    55,
                    66,
                    75,
                    57,
                    82
                ],
                "revisions": null
            },
            "hero_image": {
                "property_name": "The Golden Nugget",
                "rating_number": 65,
                "rating_category": "Needs Work",
                "feedback": {
                    "summary": "The hero image shows a cozy bedroom with clean lines, which conveys a sense of comfort and tranquility. However, for a hero image, a more vibrant and engaging representation of the property's best features could be more effective.",
                    "items": [
                        {
                            "title": "Cozy Atmosphere",
                            "feedback": "The bedroom looks cozy and inviting, ideal for a peaceful stay."
                        },
                        {
                            "title": "Simple and Clean",
                            "feedback": "The image conveys cleanliness and simplicity, which is appealing to many guests."
                        },
                        {
                            "title": "Lack of Exterior Features",
                            "feedback": "The photo does not showcase any of the property's unique outdoor features like the pool or backyard."
                        },
                        {
                            "title": "Limited Excitement",
                            "feedback": "While the image is warm, it doesn't evoke excitement or a unique sense of place."
                        },
                        {
                            "title": "Lighting and Composition",
                            "feedback": "The lighting is soft and pleasant, but the composition could be enhanced to capture more interest."
                        }
                    ]
                },
                "suggestions": [
                    "Use an exterior shot with the pool to make the listing more attractive.",
                    "Include a collage of photos to showcase multiple facets of the property.",
                    "Highlight unique amenities like the pool or BBQ area in the main image.",
                    "Consider updating the lighting to enhance the room's features.",
                    "Use a wide-angle lens to capture more of the room."
                ],
                "expert_ratings": [
                    66,
                    68,
                    65,
                    64,
                    63,
                    67,
                    66,
                    65,
                    64,
                    63,
                    62,
                    66,
                    67,
                    65,
                    68,
                    64,
                    67,
                    63,
                    64,
                    63,
                    62,
                    66,
                    65,
                    64,
                    63,
                    62,
                    67,
                    65,
                    68,
                    65,
                    64,
                    63,
                    67,
                    66,
                    66,
                    65,
                    64,
                    63,
                    62,
                    66,
                    65,
                    67,
                    66,
                    67,
                    68,
                    64,
                    65,
                    63,
                    64,
                    62,
                    67,
                    65,
                    66,
                    66,
                    65,
                    64,
                    63,
                    66,
                    65,
                    68,
                    64,
                    63,
                    68,
                    62,
                    67,
                    64,
                    66,
                    65,
                    63,
                    64,
                    63,
                    62,
                    67,
                    65,
                    66,
                    64,
                    68,
                    65,
                    66,
                    63,
                    64,
                    67,
                    66,
                    68,
                    66,
                    65,
                    63,
                    62,
                    67,
                    65,
                    66,
                    64,
                    68,
                    62,
                    67,
                    65,
                    66,
                    63,
                    64,
                    67
                ],
                "revisions": null
            },
            "other_images": {
                "property_name": "Standard Stay - STR Listing",
                "rating_number": 74,
                "rating_category": "Satisfactory",
                "feedback": {
                    "summary": "You're doing well, but there's room for a few improvements to make your photos stand out even more.",
                    "items": [
                        {
                            "title": "Lighting",
                            "feedback": "Consider enhancing the lighting in the indoor photos. Brighter images can make spaces look more inviting."
                        },
                        {
                            "title": "Composition",
                            "feedback": "The composition of your photos is generally good, but a few shots could benefit from a more dynamic angle to showcase the space better."
                        },
                        {
                            "title": "Detail Shots",
                            "feedback": "Include some close-up shots of unique details or amenities to add character to your listing."
                        },
                        {
                            "title": "Outdoor Appeal",
                            "feedback": "Your outdoor shots are clear, but adding a touch of greenery or decor could enhance the visual appeal."
                        }
                    ]
                },
                "suggestions": [
                    "Improve lighting for a brighter, more inviting look.",
                    "Experiment with angles to capture rooms more dynamically.",
                    "Add close-up shots of distinctive features or decor.",
                    "Incorporate greenery or decor in outdoor areas for added charm.",
                    "Use consistent photo editing for a uniform appearance.",
                    "Consider Hiring a Professional Photographer\n                               \n            While your photos are a good start, hiring a professional photographer could significantly elevate the visual appeal of your listing. A pro has the experience to capture your space in the best possible light, ensuring that it looks both inviting and accurate. This investment can help differentiate your property in a competitive market, where high-quality visuals can be the deciding factor for potential guests. Professional photographers are skilled in aspects like lighting, composition, and angles, which can make your property look more spacious, appealing, and true to its real-life charm.\n                               \n            For Those Who Prefer DIY Photography or Are Working Within a Budget\n                               \n            If you prefer to handle your own photography or a professional is outside your budget, here are a few simple tips to help improve your photos:\n                               \n            Maximize Natural Light: Aim to shoot during the day when natural light is abundant. Open all windows, use light-colored curtains, and avoid harsh overhead lights. Natural light enhances the warmth and appeal of the space, making it feel more inviting.\n                               \n            Use Wide Angles: When photographing rooms, use wide-angle shots to capture the entire space. This helps give viewers a sense of the room's size and layout. Avoid tight or cluttered shots, as they can make the space feel smaller than it actually is.\n                               \n            Focus on Clean and Tidy Staging: Before you take the photo, clear away any clutter. Neatly arrange furniture and decor to make the space look polished and functional. The simpler and more streamlined the space appears, the more likely it is to resonate with potential guests."
                ],
                "expert_ratings": [
                    72,
                    75,
                    73,
                    74,
                    76,
                    77,
                    78,
                    69,
                    70,
                    71,
                    71,
                    76,
                    75,
                    79,
                    74,
                    70,
                    68,
                    77,
                    75,
                    73,
                    72,
                    78,
                    69,
                    74,
                    73,
                    77,
                    78,
                    76,
                    70,
                    71,
                    73,
                    75,
                    74,
                    76,
                    71,
                    72,
                    68,
                    69,
                    78,
                    76,
                    75,
                    74,
                    73,
                    77,
                    76,
                    77,
                    72,
                    73,
                    71,
                    74,
                    72,
                    75,
                    76,
                    77,
                    69,
                    68,
                    75,
                    78,
                    74,
                    70,
                    73,
                    72,
                    74,
                    76,
                    75,
                    77,
                    69,
                    71,
                    72,
                    75,
                    74,
                    73,
                    78,
                    77,
                    76,
                    72,
                    74,
                    71,
                    73,
                    77,
                    76,
                    78,
                    77,
                    74,
                    72,
                    69,
                    72,
                    75,
                    74,
                    73,
                    78,
                    77,
                    70,
                    72,
                    71,
                    76,
                    74,
                    75,
                    72,
                    73
                ],
                "revisions": null
            },
            "interior_design": {
                "property_name": "The Golden Nugget",
                "rating_number": 78,
                "rating_category": "Satisfactory",
                "feedback": {
                    "summary": "The Golden Nugget has a soothing and functional design that's well-suited for traveling professionals, creating a pleasant atmosphere for guests.",
                    "items": [
                        {
                            "title": "Color Palette",
                            "feedback": "The use of neutral colors contributes to a calming ambiance, but adding some vibrant accents could enhance the overall decor."
                        },
                        {
                            "title": "Furniture Arrangement",
                            "feedback": "The furniture layout maximizes space and functionality, though some areas feel slightly cluttered."
                        },
                        {
                            "title": "Lighting Options",
                            "feedback": "Natural light flows well into the space; incorporating more layered lighting options could improve the evening atmosphere."
                        },
                        {
                            "title": "Outdoor Area",
                            "feedback": "The pool area is a fantastic feature, yet the surrounding seating could be more inviting and comfortable."
                        },
                        {
                            "title": "Kitchen Essentials",
                            "feedback": "The kitchen is well-stocked with necessary essentials but could benefit from modern appliances for enhanced convenience."
                        }
                    ]
                },
                "suggestions": [
                    "Add pops of color through accessories like cushions and art.",
                    "Rearrange furniture for a more spacious feel in common areas.",
                    "Introduce softer lighting options for relaxing evenings.",
                    "Create a more inviting outdoor space with comfortable seating near the pool.",
                    "Upgrade kitchen appliances to modern standards for guests' convenience."
                ],
                "expert_ratings": [
                    45,
                    67,
                    72,
                    64,
                    89,
                    91,
                    75,
                    53,
                    94,
                    78,
                    86,
                    80,
                    55,
                    66,
                    81,
                    70,
                    65,
                    60,
                    53,
                    77,
                    58,
                    59,
                    63,
                    62,
                    48,
                    69,
                    74,
                    73,
                    92,
                    71,
                    54,
                    52,
                    90,
                    46,
                    99,
                    57,
                    88,
                    37,
                    68,
                    50,
                    76,
                    83,
                    34,
                    44,
                    93,
                    31,
                    42,
                    39,
                    82,
                    35,
                    40,
                    72,
                    47,
                    36,
                    89,
                    49,
                    41,
                    32,
                    33,
                    38,
                    15,
                    74,
                    62,
                    23,
                    85,
                    84,
                    18,
                    12,
                    20,
                    19,
                    13,
                    27,
                    11,
                    4,
                    2,
                    1,
                    3,
                    17,
                    8,
                    14,
                    5,
                    30,
                    6,
                    60,
                    29,
                    10,
                    16,
                    9,
                    12,
                    26,
                    24,
                    25,
                    75,
                    59,
                    83,
                    37,
                    88,
                    35,
                    91,
                    66,
                    78,
                    94,
                    72,
                    88,
                    56,
                    70,
                    73
                ],
                "revisions": null
            },
            "overall_ratings": {
                "property_name": "The Golden Nugget",
                "rating_number": 72,
                "rating_category": "Satisfactory",
                "feedback": {
                    "summary": "Your Airbnb listing has room for improvement in several areas, primarily in enhancing engagement and clarity. Focusing on the description, title, and visuals will greatly influence guest attraction.",
                    "items": [
                        {
                            "title": "Engaging Descriptions",
                            "feedback": "A warmer, more inviting tone in your property description will entice potential guests."
                        },
                        {
                            "title": "Title Specificity",
                            "feedback": "The title needs to highlight unique features, enhancing its appeal."
                        },
                        {
                            "title": "Visual Enhancements",
                            "feedback": "Quality photos that showcase the property’s strengths, including outdoor areas, are essential."
                        },
                        {
                            "title": "Optimize Amenities",
                            "feedback": "Clarifying guest access to amenities can help manage expectations and attract a broader audience."
                        },
                        {
                            "title": "Showcase Unique Features",
                            "feedback": "Emphasizing standout features like a pool could draw more inquiries."
                        }
                    ]
                },
                "suggestions": [
                    "Make your property descriptions more inviting and detailed.",
                    "Highlight unique features like a pool or a cozy outdoor space.",
                    "Update title to include 'central location' or 'ideal for professionals'.",
                    "Consider hiring a professional photographer to enhance visual appeal.",
                    "Clarify guest access arrangements for shared spaces."
                ],
                "expert_ratings": [
                    54,
                    61,
                    75,
                    39,
                    48,
                    81,
                    74,
                    85,
                    80,
                    72,
                    69,
                    50,
                    67,
                    31,
                    39,
                    64,
                    70,
                    82,
                    52,
                    59,
                    66,
                    49,
                    81,
                    88,
                    66,
                    47,
                    50,
                    78,
                    37,
                    45,
                    63,
                    65,
                    72,
                    55,
                    50,
                    90,
                    41,
                    89,
                    54,
                    62,
                    70,
                    71,
                    73,
                    56,
                    55,
                    28,
                    40,
                    82,
                    33,
                    54,
                    28,
                    66,
                    84,
                    76,
                    19,
                    17,
                    93,
                    58,
                    69,
                    33,
                    80,
                    46,
                    66,
                    90,
                    57,
                    80,
                    50,
                    55,
                    29,
                    73,
                    66,
                    76,
                    69,
                    71,
                    86,
                    42,
                    27,
                    20,
                    19,
                    53,
                    84,
                    52,
                    45,
                    71,
                    74,
                    68,
                    78,
                    85,
                    76,
                    56,
                    89,
                    80,
                    81,
                    64,
                    74,
                    48
                ],
                "revisions": null
            }
        }
    ]
}