

interface RatingCategory {
    name: string
    score: number
    category: string
    icon: React.ReactNode
    feedback: string
    suggestions: string
    description_rewrite?: any
    title_rewrites?: string
}

interface PropertyRatingsProps {
    ratings: {
        description: any
        title: any
        amenities: any
        heroImage: any
        otherImages: any
        interiorDesign: any
        feedback: any
        suggestions: any
        description_rewrite?: any
        title_rewrites?: any
        overall_rating_number: any
        overall_rating_category: any
    }
}

// export const getMockRatings = () => {
//     const rawRatings = MockRatingsSample;

//     if (!rawRatings) {
//         console.log("No ratings data available", rawRatings);
//         return {}
//     }

//     const ratings: PropertyRatingsProps = {
//         ratings: {
//             description: rawRatings.description,
//             title: rawRatings.title,
//             amenities: rawRatings.amenities,
//             heroImage: rawRatings.hero_image,
//             otherImages: rawRatings.other_images,
//             interiorDesign: rawRatings.interior_design,
//             feedback: rawRatings.overall_ratings.feedback.summary,
//             suggestions: rawRatings.overall_ratings.suggestions,
//             description_rewrite: rawRatings.description.description_rewrite,
//             title_rewrites: rawRatings.title.title_rewrites,
//             overall_rating_number: rawRatings.overall_ratings.rating_number,
//             overall_rating_category: rawRatings.overall_ratings.rating_category
//         }
//     };

//     console.log("Formatted ratings:", ratings);
//     return ratings;
// }

export const MockRatingsSample = {
    "ratings": {
        "title": {
            "property_name": "The Golden Nugget",
            "rating_number": 84,
            "rating_category": "Good",
            "feedback": {
                "summary": "The title 'The Golden Nugget' is catchy and memorable, instantly evoking a sense of value and uniqueness. However, it does lack some specific elements that could enhance its appeal to potential guests.",
                "items": [
                    {
                        "title": "Catchy Name",
                        "feedback": "The name 'The Golden Nugget' is intriguing and stands out."
                    },
                    {
                        "title": "Location Clarity",
                        "feedback": "Consider adding where it's located to give context, like 'in Yuma'."
                    },
                    {
                        "title": "Descriptive Aspect",
                        "feedback": "The title could benefit from adding a descriptor such as 'Quiet Retreat' or 'Poolside Stay'."
                    },
                    {
                        "title": "Vague Terms",
                        "feedback": "The term 'Nugget' is somewhat vague; it doesn’t immediately convey that it's a rental property."
                    },
                    {
                        "title": "Target Audience",
                        "feedback": "Mentioning amenities or target audience in the title could better attract guests."
                    }
                ]
            },
            "suggestions": [
                "Add location to the title for clarity.",
                "Include features like 'pool' or 'central location'.",
                "Use descriptive adjectives to enhance appeal."
            ],
            "expert_ratings": [
                66,
                75,
                72,
                88,
                90,
                67,
                70,
                82,
                85,
                76,
                68,
                69,
                80,
                78,
                91,
                74,
                77,
                86,
                89,
                73,
                84,
                66,
                70,
                72,
                88,
                83,
                65,
                76,
                80,
                92,
                68,
                74,
                82,
                72,
                78,
                79,
                85,
                67,
                70,
                80,
                69,
                90,
                83,
                77,
                87,
                65,
                92,
                71,
                78,
                66,
                68,
                74,
                82,
                73,
                87,
                88,
                66,
                70,
                72,
                84,
                68,
                79,
                90,
                75,
                91,
                76,
                67,
                62,
                86,
                85,
                88,
                73,
                92,
                67,
                72,
                79,
                81,
                88,
                75,
                86,
                73,
                71,
                82,
                85,
                68,
                77,
                66,
                67,
                92,
                82,
                89,
                70,
                76,
                85,
                68,
                91,
                89,
                75,
                90,
                81,
                67,
                66,
                78,
                84,
                89,
                70,
                88,
                82
            ],
            "title_rewrites": [
                "The Golden Nugget: Your Quiet Retreat in Yuma",
                "Relax at The Golden Nugget with Pool Access",
                "Centrally Located Golden Nugget - Ideal for Professionals"
            ],
            "revisions": [
                "The Golden Nugget: Poolside Oasis in Yuma",
                "Golden Nugget Getaway: Central Location & Comfort",
                "Peaceful Retreat at The Golden Nugget with Pool Access"
            ]
        },
        "description": {
            "property_name": "The Golden Nugget",
            "rating_number": 65,
            "rating_category": "Needs Work",
            "feedback": {
                "summary": "Your listing has some good points, but there are areas that could use enhancement for a more compelling presentation.",
                "items": [
                    {
                        "title": "Location Information",
                        "feedback": "While you've provided some distances to key locations, more detail about attractions or restaurants nearby could help guests envision their stay better."
                    },
                    {
                        "title": "Amenities Section",
                        "feedback": "You've listed many amenities but consider structuring it more clearly to showcase what makes your property unique."
                    },
                    {
                        "title": "Engaging Language",
                        "feedback": "Using more engaging and descriptive language can make the listing sound more inviting and exciting."
                    },
                    {
                        "title": "Highlight the Pool Features",
                        "feedback": "The pool is a great feature! Emphasize its condition and usability, maybe even include activities guests can enjoy."
                    },
                    {
                        "title": "Guest Experience",
                        "feedback": "Sharing more about what makes The Golden Nugget memorable for guests could entice more bookings."
                    }
                ]
            },
            "suggestions": [
                "Include more local attractions and experiences nearby to attract guests.",
                "Revise the amenities section for clarity and highlight unique features.",
                "Use descriptive language to make the listing more engaging and inviting.",
                "Provide tips or recommendations for using the pool and outdoor spaces.",
                "Add a personal touch by sharing your story or what inspired you to create this space."
            ],
            "expert_ratings": [
                82,
                67,
                74,
                55,
                72,
                68,
                62,
                77,
                59,
                64,
                70,
                81,
                75,
                60,
                78,
                69,
                63,
                74,
                71,
                66,
                61,
                52,
                57,
                80,
                76,
                79,
                54,
                75,
                68,
                73,
                66,
                82,
                91,
                66,
                75,
                65,
                58,
                53,
                78,
                63,
                77,
                55,
                84,
                58,
                83,
                72,
                61,
                64,
                66,
                68,
                62,
                72,
                74,
                68,
                71,
                67,
                82,
                70,
                56,
                83,
                60,
                54,
                85,
                62,
                54,
                75,
                67,
                77,
                69,
                68,
                63,
                80,
                64,
                59,
                81,
                57,
                55,
                60,
                71,
                67,
                68,
                74,
                90,
                62,
                69,
                72,
                57,
                82,
                69,
                68,
                81,
                67,
                70,
                73,
                66,
                61,
                85,
                78,
                69,
                74,
                61,
                76,
                72,
                63,
                75,
                67,
                85,
                82,
                78,
                84
            ],
            "description_rewrite": {
                "listing_description": "Welcome to The Golden Nugget! Enjoy a peaceful stay in the heart of Yuma, AZ, just minutes from key destinations. This tranquil home offers a fully equipped kitchen, spacious living areas, and a year-round pool to unwind in the Arizona sun. Perfect for professionals or families seeking comfort and relaxation. With a nearby walking path, embrace nature right at your doorstep!",
                "your_property": "The Golden Nugget is your home away from home, featuring a full kitchen, a cozy living room, and inviting dining areas. The backyard boasts a refreshing pool, ideal for socializing with fellow guests or relaxing. Enjoy all the comforts necessary for a pleasant stay!",
                "guest_access": "You will have full access to the kitchen, living room, dining room, and backyard pool. Shared spaces are available with other guests in the additional rooms, allowing for social interactions while ensuring privacy as well.",
                "interaction_with_guests": "I am happy to assist you during your stay at The Golden Nugget. Enjoy your time here and feel free to reach out for recommendations or assistance!",
                "other_details_to_note": "Please note that pets are welcome! Enjoy the convenience of self check-in and free parking on-site."
            },
            "revisions": null
        },
        "amenities": {
            "property_name": "Standard Stay Property",
            "rating_number": 76,
            "rating_category": "Satisfactory",
            "feedback": {
                "summary": "Overall, your property provides a solid selection of amenities for standard stays, making it appealing for various guests.",
                "items": [
                    {
                        "title": "Essential Amenities",
                        "feedback": "You include a number of essential amenities like towels, bed linens, and toiletries, which enhances guest comfort."
                    },
                    {
                        "title": "Kitchen Facilities",
                        "feedback": "The kitchen is well-appointed with cooking essentials, allowing guests the convenience of preparing their meals."
                    },
                    {
                        "title": "Privacy and Safety Features",
                        "feedback": "It's great to see smoke alarms and other safety features available, contribute to a safe environment."
                    },
                    {
                        "title": "Outdoor Amenities",
                        "feedback": "Having a backyard and BBQ grill adds a nice touch for guests who enjoy outdoor experiences."
                    },
                    {
                        "title": "TV and Entertainment",
                        "feedback": "Including a TV is a plus for entertainment, but consider adding streaming services to enhance the experience."
                    }
                ]
            },
            "suggestions": [
                "Consider adding a few more entertainment options, such as board games or books.",
                "Invest in quality outdoor furniture for the backyard to create a more inviting space.",
                "Provide additional kitchen appliances like a slow cooker or blender to accommodate diverse cooking needs.",
                "Enhance guest comfort by offering cozy blankets in the living area."
            ],
            "expert_ratings": [
                43,
                76,
                55,
                85,
                68,
                79,
                66,
                54,
                79,
                74,
                39,
                80,
                48,
                63,
                77,
                88,
                56,
                61,
                72,
                60,
                73,
                90,
                64,
                52,
                38,
                84,
                71,
                49,
                58,
                87,
                36,
                50,
                92,
                53,
                44,
                70,
                47,
                81,
                83,
                62,
                91,
                57,
                55,
                42,
                75,
                34,
                89,
                40,
                78,
                95,
                94,
                86,
                69,
                65,
                37,
                59,
                70,
                41,
                50,
                80,
                54,
                87,
                93,
                96,
                31,
                67,
                52,
                33,
                79,
                83,
                72,
                99,
                71,
                45,
                48,
                22,
                26,
                46,
                91,
                38,
                88,
                27,
                29,
                33,
                66,
                4,
                19,
                90,
                81,
                57,
                12,
                71,
                32,
                77,
                50,
                56,
                85,
                15,
                28,
                1
            ],
            "revisions": null
        },
        "hero_image": {
            "property_name": "The Golden Nugget",
            "rating_number": 68,
            "rating_category": "Needs Work",
            "feedback": {
                "summary": "The hero image of 'The Golden Nugget' presents a cozy bedroom but lacks standout features to make it memorable. Its simplicity is appealing, but it doesn’t capture the unique amenities mentioned in the listing.",
                "items": [
                    {
                        "title": "Cozy Feel",
                        "feedback": "The bedroom looks warm and inviting, thanks to the rich colors and soft lighting."
                    },
                    {
                        "title": "Lack of Unique Features",
                        "feedback": "The image doesn't highlight any of the unique selling points like the pool or outdoor spaces."
                    },
                    {
                        "title": "Basic Composition",
                        "feedback": "While the image is clear, it lacks composition elements that might make it stand out."
                    }
                ]
            },
            "suggestions": [
                "Consider featuring the pool in the hero image to attract those interested in outdoor relaxation.",
                "Include a wider shot that captures more of the room’s features or amenities.",
                "Use brighter lighting in future images to enhance the room's appeal.",
                "Add elements like a vase of fresh flowers or a neatly folded blanket to create a welcoming atmosphere.",
                "Incorporate outdoor views through the window to connect the indoor space with the location."
            ],
            "expert_ratings": [
                72,
                64,
                70,
                66,
                67,
                68,
                69,
                71,
                65,
                62,
                73,
                64,
                68,
                70,
                69,
                66,
                65,
                67,
                74,
                61,
                63,
                68,
                72,
                69,
                70,
                67,
                62,
                65,
                73,
                68,
                71,
                66,
                69,
                64,
                71,
                67,
                66,
                70,
                63,
                65,
                74,
                68,
                72,
                69,
                66,
                67,
                64,
                63,
                71,
                68,
                66,
                65,
                68,
                69,
                70,
                61,
                72,
                67,
                73,
                64,
                70,
                69,
                68,
                71,
                67,
                66,
                73,
                65,
                70,
                69,
                68,
                64,
                66,
                71,
                74,
                62,
                65,
                69,
                67,
                72,
                63,
                70,
                67,
                68,
                71,
                66,
                69,
                65,
                70,
                61,
                68,
                72,
                64,
                73,
                67,
                69,
                68,
                66,
                67,
                70
            ],
            "revisions": null
        },
        "other_images": {
            "property_name": "Standard Stay Property",
            "rating_number": 68,
            "rating_category": "Needs Work",
            "feedback": {
                "summary": "Your property's photos are decent, offering a good representation of the space, though they could be enhanced to make the listing stand out more.",
                "items": [
                    {
                        "title": "Lighting",
                        "feedback": "Consider improving the lighting in some of the photos to give a brighter and more inviting atmosphere."
                    },
                    {
                        "title": "Angles and Composition",
                        "feedback": "Try capturing photos from different angles and compositions to provide a more dynamic view of each room."
                    },
                    {
                        "title": "Color Balance",
                        "feedback": "Adjusting the color balance could make the rooms appear more vibrant and appealing."
                    }
                ]
            },
            "suggestions": [
                "Enhance lighting in your photos to make the rooms feel larger and more welcoming.",
                "Experiment with different photographic angles to showcase the space better.",
                "Consider using photo editing tools to adjust color balance for a more lively appearance.",
                "Add some decor elements to make the rooms look more inviting.",
                "Consider Hiring a Professional Photographer\n                               \n            While your photos are a good start, hiring a professional photographer could significantly elevate the visual appeal of your listing. A pro has the experience to capture your space in the best possible light, ensuring that it looks both inviting and accurate. This investment can help differentiate your property in a competitive market, where high-quality visuals can be the deciding factor for potential guests. Professional photographers are skilled in aspects like lighting, composition, and angles, which can make your property look more spacious, appealing, and true to its real-life charm.\n                               \n            For Those Who Prefer DIY Photography or Are Working Within a Budget\n                               \n            If you prefer to handle your own photography or a professional is outside your budget, here are a few simple tips to help improve your photos:\n                               \n            Maximize Natural Light: Aim to shoot during the day when natural light is abundant. Open all windows, use light-colored curtains, and avoid harsh overhead lights. Natural light enhances the warmth and appeal of the space, making it feel more inviting.\n                               \n            Use Wide Angles: When photographing rooms, use wide-angle shots to capture the entire space. This helps give viewers a sense of the room's size and layout. Avoid tight or cluttered shots, as they can make the space feel smaller than it actually is.\n                               \n            Focus on Clean and Tidy Staging: Before you take the photo, clear away any clutter. Neatly arrange furniture and decor to make the space look polished and functional. The simpler and more streamlined the space appears, the more likely it is to resonate with potential guests."
            ],
            "expert_ratings": [
                72,
                67,
                69,
                70,
                65,
                68,
                66,
                72,
                63,
                71,
                68,
                70,
                64,
                72,
                68,
                65,
                67,
                71,
                69,
                70,
                66,
                72,
                69,
                67,
                64,
                71,
                68,
                66,
                72,
                65,
                68,
                70,
                63,
                71,
                69,
                67,
                64,
                71,
                68,
                70,
                66,
                69,
                67,
                72,
                64,
                68,
                70,
                67,
                71,
                69,
                66,
                72,
                69,
                65,
                68,
                68,
                72,
                70,
                71,
                69,
                66,
                64,
                72,
                67,
                70,
                68,
                64,
                71,
                69,
                66,
                72,
                65,
                69,
                67,
                68,
                71,
                70,
                65,
                67,
                72,
                66,
                68,
                70,
                72,
                69,
                64,
                71,
                66,
                68,
                65,
                70,
                67,
                72,
                69,
                64,
                71,
                68,
                66,
                67,
                70
            ],
            "revisions": null
        },
        "interior_design": {
            "property_name": "The Golden Nugget",
            "rating_number": 80,
            "rating_category": "Satisfactory",
            "feedback": {
                "summary": "Your property has a welcoming and peaceful ambiance, perfect for both relaxation and professional stays. However, slight enhancements in decor and comfort could elevate the guest experience further.",
                "items": [
                    {
                        "title": "Color Scheme",
                        "feedback": "The color scheme is calm and inviting, but consider incorporating pops of color to add vibrancy."
                    },
                    {
                        "title": "Furniture Quality",
                        "feedback": "The furniture is functional, but investing in higher-quality pieces could enhance comfort and style."
                    },
                    {
                        "title": "Lighting",
                        "feedback": "The natural light enhances the space; however, consider layering lighting options for ambiance during the evening."
                    },
                    {
                        "title": "Outdoor Area",
                        "feedback": "The pool area is great for relaxation, perhaps adding some outdoor furniture would enhance usability."
                    },
                    {
                        "title": "Artwork and Decor",
                        "feedback": "Consider adding artwork or decorative pieces that reflect the local culture for a unique touch."
                    }
                ]
            },
            "suggestions": [
                "Incorporate vibrant decor elements for a livelier atmosphere.",
                "Upgrade furniture to improve comfort and aesthetic appeal.",
                "Add ambient lighting options for enhanced evening usage.",
                "Include outdoor furniture to utilize the pool area better.",
                "Integrate local artwork to create a unique atmosphere."
            ],
            "expert_ratings": [
                74,
                68,
                82,
                90,
                75,
                88,
                80,
                70,
                77,
                66,
                85,
                91,
                83,
                78,
                72,
                81,
                67,
                76,
                84,
                89,
                73,
                65,
                87,
                95,
                92,
                94,
                81,
                69,
                79,
                79,
                74,
                68,
                82,
                90,
                75,
                88,
                80,
                70,
                77,
                66,
                85,
                91,
                83,
                78,
                72,
                81,
                67,
                76,
                84,
                89,
                73,
                65,
                87,
                95,
                92,
                94,
                81,
                69,
                79,
                79,
                74,
                68,
                82,
                90,
                75,
                88,
                80,
                70,
                77,
                66,
                85,
                91,
                83,
                78,
                72,
                81,
                67,
                76,
                84,
                89,
                73,
                65,
                87,
                95,
                92,
                94,
                81,
                69,
                79,
                76,
                77,
                78
            ],
            "revisions": null
        },
        "overall_ratings": {
            "property_name": "The Golden Nugget",
            "rating_number": 73,
            "rating_category": "Satisfactory",
            "feedback": {
                "summary": "Overall, 'The Golden Nugget' presents a promising option for potential guests, but several areas need enhancement for improved appeal and guest experience.",
                "items": [
                    {
                        "title": "Title and Description Clarity",
                        "feedback": "The title 'The Golden Nugget' is catchy but could benefit from more descriptive elements regarding its location and features."
                    },
                    {
                        "title": "Engaging Listing",
                        "feedback": "The listing could use more vivid and engaging language to better attract potential guests."
                    },
                    {
                        "title": "Visual Appeal",
                        "feedback": "The current images, especially the hero image, do not highlight the unique selling points like the pool."
                    },
                    {
                        "title": "Local Insights",
                        "feedback": "More details on nearby attractions and experiences could enhance the guest's anticipation of their stay."
                    },
                    {
                        "title": "Decor and Comfort Improvements",
                        "feedback": "While the interior design presents a calming ambiance, small touches can enhance comfort and guest experience."
                    }
                ]
            },
            "suggestions": [
                "Revise the title to include location and unique features.",
                "Use more engaging language in the listing description.",
                "Invest in high-quality photography that showcases the property’s best features.",
                "Add local recommendations to enrich the guest experience.",
                "Enhance decor and comfort of the space for a better stay."
            ],
            "expert_ratings": [
                66,
                75,
                72,
                88,
                90,
                67,
                70,
                82,
                85,
                76,
                68,
                69,
                80,
                78,
                91,
                74,
                77,
                86,
                89,
                73,
                84,
                66,
                70,
                72,
                88,
                83,
                65,
                76,
                80,
                92,
                68,
                74,
                82,
                72,
                78,
                79,
                85,
                67,
                70,
                80,
                69,
                90,
                83,
                77,
                87,
                65,
                92,
                71,
                78,
                66,
                68,
                74,
                82,
                73,
                87,
                88,
                66,
                70,
                72,
                84,
                68,
                79,
                90,
                75,
                91,
                76,
                67,
                62,
                86,
                85,
                88,
                73,
                92,
                67,
                72,
                79,
                81,
                88,
                75,
                86,
                73,
                71,
                82,
                85,
                68,
                77,
                66,
                67,
                92,
                82,
                89,
                70,
                76,
                85,
                68,
                91,
                89,
                75,
                90,
                81,
                67,
                66,
                78,
                84,
                89,
                70,
                88,
                82
            ],
            "revisions": null
        }
    }
}