import HeaderNav from '@/components/header'
import '../globals.css'
import { ThemeProvider } from '../providers'
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/ui/resizable"
import { Sidebar } from '@/components/sidebar'
// import UserContext from "@/app/UserContext";
import { useState } from 'react'
import { createClient } from '@/utils/supabase/server'


export const metadata = {
  title: 'User Management',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const supabase = createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser()

  return (
    <html lang="en" suppressHydrationWarning>
      <body className="p-5">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <HeaderNav />

          <ResizablePanelGroup
            direction="horizontal"
            className="min-h-[600px] w-full"
          >
            <ResizablePanel defaultSize={20} className="min-w-[150px]">
              <div className="flex h-full justify-center p-6 pt-[100px]">
                <Sidebar />
              </div>
            </ResizablePanel>
            <ResizableHandle withHandle />
            <ResizablePanel defaultSize={80}>
              <div className="flex h-full justify-center p-6">
                <div className="container">
                  {/* <UserContext.Provider value={{ user }}> */}
                  {children}
                  {/* </UserContext.Provider> */}
                </div>
              </div>
            </ResizablePanel>
          </ResizablePanelGroup>

        </ThemeProvider>
      </body>
    </html>
  )
}
