import './globals.css'
import { ThemeProvider } from './providers'
import { createClient } from '@/utils/supabase/server'
import { PostHogTracker } from "./PostHogTracker";
import HeaderNav from '@/components/header';
import Footer from '@/components/footer';

export const metadata = {
  title: 'User Management',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const supabase = createClient();
  const { data } = await supabase.auth.getUser()

  return (
    <html lang="en" suppressHydrationWarning>
      <body className="px-5 bg-muted">
        <PostHogTracker>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <div className="min-h-screen">
              {children}
              <Footer />
            </div>
          </ThemeProvider>
        </PostHogTracker>
      </body>
    </html>
  )
}