export const mockResults = {
    "ratings":
    {
        "title": {
            "property_name": "Two Story House w/ Balcony and Patio on the Beach",
            "rating_number": 85,
            "rating_category": "good",
            "feedback": {
                "summary": "Your home's title is catchy and accurately describes some key features like the balcony, patio, and beach location. However, it could be slightly improved by including more specific details that highlight its unique selling points.",
                "items": [
                    {
                        "title": "Descriptive Titles",
                        "feedback": "Your title clearly highlights that the property is a two-story house with a balcony and patio on the beach, which is attractive and concise."
                    },
                    {
                        "title": "Specificity and Attraction",
                        "feedback": "While the title is good, adding details such as the number of bedrooms or luxurious elements could help catch the eye of those seeking a bit more information at a glance."
                    },
                    {
                        "title": "Beachfront Highlight",
                        "feedback": "Emphasizing the direct beach access could be more prominent in your title, making it stand out even more to potential guests looking for a beachfront experience."
                    }
                ]
            },
            "suggestions": [
                "Include the number of bedrooms in the title to provide more information.",
                "Highlight the direct beach access more prominently in the title.",
                "Consider mentioning a unique feature like the fire-pit or BBQ for added attraction."
            ],
            "expert_ratings": [
                90,
                86,
                84,
                82,
                85,
                89,
                87,
                88,
                84,
                83,
                91,
                82,
                86,
                88,
                87,
                84,
                85,
                86,
                83,
                82,
                88,
                90,
                84,
                85,
                86,
                87,
                88,
                85,
                86,
                89,
                84,
                82,
                85,
                86,
                87,
                81,
                89,
                86,
                88,
                85,
                86,
                85,
                88,
                87,
                84,
                85,
                90,
                88,
                86,
                84,
                87,
                86,
                88,
                85,
                84,
                83,
                86,
                87,
                85,
                88,
                86,
                90,
                85,
                87,
                84,
                82,
                86,
                88,
                87,
                84,
                85,
                86,
                85,
                89,
                88,
                87,
                86,
                84,
                85,
                83,
                87,
                88,
                84,
                85,
                84,
                86,
                88,
                82,
                84,
                87,
                86,
                85,
                83,
                86,
                85,
                84,
                87,
                88,
                89,
                85
            ],
            "revisions": [
                "Two-Story 3BR Beachfront House w/ Balcony & Patio",
                "Beachfront Family Home w/ Oversized Patio & Fire-pit",
                "Luxurious 3BR Beach House w/ Direct Sand Access"
            ]
        },
        "description": {
            "property_name": "Two Story House w/ Balcony and Patio on the Beach",
            "rating_number": 92,
            "rating_category": "excellent",
            "feedback": {
                "summary": "This beachside home offers an idyllic retreat with its stunning location and ample amenities, making it perfect for families seeking a tranquil getaway. The unobstructed ocean views and easy beach access set it apart.",
                "items": [
                    {
                        "title": "Unbeatable Location",
                        "feedback": "You can't beat the location of this home, which is one of the closest to the ocean in Newport Beach. The convenience of stepping right onto the sand is a huge draw."
                    },
                    {
                        "title": "Family-Friendly Amenities",
                        "feedback": "The home's layout is perfect for families, with comfortable sleeping arrangements and safety considerations for those with mobility issues."
                    },
                    {
                        "title": "Outdoor Living at its Best",
                        "feedback": "The spacious balcony and patio areas provide excellent opportunities for outdoor dining and relaxation with views that are hard to match."
                    }
                ]
            },
            "suggestions": [
                "Consider adding central air conditioning for added comfort during hot weather.",
                "Enhance the description with professional photographs to better capture the property's charm.",
                "Simplify house rules to make them easier to understand for potential guests."
            ],
            "expert_ratings": [
                95,
                93,
                94,
                90,
                88,
                91,
                92,
                94,
                86,
                95,
                91,
                92,
                90,
                93,
                95,
                89,
                87,
                92,
                91,
                90,
                88,
                94,
                92,
                95,
                93,
                91,
                90,
                89,
                94,
                92,
                95,
                93,
                92,
                94,
                93,
                90,
                92,
                88,
                89,
                94,
                95,
                93,
                91,
                89,
                90,
                92,
                94,
                95,
                93,
                91,
                90,
                94,
                92,
                88,
                89,
                91,
                90,
                94,
                92,
                91,
                93,
                95,
                86,
                88,
                92,
                95,
                91,
                94,
                90,
                88,
                93,
                92,
                91,
                95,
                94,
                93,
                92,
                91,
                90,
                89,
                92,
                94,
                88,
                90,
                93,
                95,
                87,
                91,
                92,
                95,
                88,
                89,
                92,
                90,
                94,
                93,
                92,
                91,
                90,
                88
            ],
            "revisions": null
        },
        "amenities": {
            "property_name": "Two Story House w/ Balcony and Patio on the Beach",
            "rating_number": 89,
            "rating_category": "excellent",
            "feedback": {
                "summary": "Your beach house offers a tremendous array of amenities that ensure a comfortable, luxurious stay. Guests will truly enjoy the direct access to the beach, the extensive array of outdoor amenities, and thoughtful touches like the well-equipped kitchen and laundry facilities.",
                "items": [
                    {
                        "title": "Spectacular Beach Access",
                        "feedback": "Your direct access to the beach, without any boardwalk obstruction, is a significant advantage. Guests love being able to walk directly onto the sand."
                    },
                    {
                        "title": "Outdoor Leisure Opportunities",
                        "feedback": "The spacious patio and balcony with outdoor dining, lounge chairs, and a fire pit are outstanding features that guests appreciate for relaxation and socializing."
                    },
                    {
                        "title": "Comprehensive Kitchen Amenities",
                        "feedback": "Having a fully equipped kitchen with everything from a gas BBQ to pots and pans allows guests to enjoy home-cooked meals conveniently."
                    },
                    {
                        "title": "Comfortable Sleeping Arrangements",
                        "feedback": "Offering varied sleeping arrangements such as a king-sized bed, queen bed, and bunk beds ensures guests have flexibility and comfort."
                    },
                    {
                        "title": "Well-Stocked Essentials",
                        "feedback": "Guests appreciate the provision of essentials like linens, beach and bath towels, and toiletries, adding to the convenience of their stay."
                    }
                ]
            },
            "suggestions": [
                "Consider installing permanent air conditioning instead of renting portable units to enhance guest comfort, especially in the summer months.",
                "Add outdoor lighting to the patio and balcony areas to enhance safety and ambiance for evening use.",
                "Improve the soundproofing of the home to mitigate noise from neighboring properties or beachgoers."
            ],
            "expert_ratings": [
                75,
                92,
                88,
                94,
                82,
                85,
                90,
                87,
                86,
                84,
                79,
                83,
                90,
                89,
                78,
                87,
                86,
                88,
                91,
                85,
                84,
                89,
                92,
                93,
                91,
                88,
                82,
                81,
                79,
                89,
                87,
                92,
                88,
                90,
                94,
                89,
                79,
                85,
                83,
                81,
                88,
                86,
                90,
                84,
                89,
                85,
                87,
                83,
                91,
                80,
                78,
                82,
                76,
                84,
                78,
                89,
                85,
                86,
                92,
                91,
                93,
                83,
                79,
                88,
                87,
                82,
                90,
                91,
                85,
                84,
                91,
                77,
                82,
                90,
                79,
                85,
                83,
                88,
                86,
                92,
                84,
                87,
                89,
                81,
                80,
                88,
                83,
                90,
                89,
                85,
                82,
                88,
                79,
                81,
                77,
                84,
                86,
                78,
                83,
                89
            ],
            "revisions": null
        },
        "hero_image": {
            "property_name": "Two Story House w/ Balcony and Patio on the Beach",
            "rating_number": 85,
            "rating_category": "excellent",
            "feedback": {
                "summary": "Your hero image beautifully captures the unique oceanfront location of your home, highlighting its direct beach access and stunning views. It successfully draws attention to the spacious outdoor area, making it a compelling first impression for potential guests.",
                "items": [
                    {
                        "title": "Stunning Ocean View",
                        "feedback": "The image perfectly captures the breathtaking ocean view, which is a major highlight for guests seeking a beachfront experience."
                    },
                    {
                        "title": "Spacious Outdoor Area",
                        "feedback": "The image showcases the ample outdoor space, including the patio and balcony, emphasizing the outdoor dining setup which is very appealing."
                    },
                    {
                        "title": "Direct Beach Access",
                        "feedback": "The direct pathway to the beach shown in the image underscores the convenience and uniqueness of the property's location."
                    }
                ]
            },
            "suggestions": [
                "Enhance the color contrast to make the image more vibrant and eye-catching.",
                "Consider adding people enjoying the outdoor area to convey a lively atmosphere.",
                "Include a shot with the outdoor fire-pit lit to highlight evening ambiance."
            ],
            "expert_ratings": [
                95,
                88,
                82,
                91,
                79,
                85,
                90,
                83,
                78,
                86,
                89,
                91,
                84,
                75,
                87,
                92,
                80,
                77,
                84,
                89,
                82,
                93,
                85,
                88,
                87,
                76,
                92,
                81,
                79,
                90,
                94,
                82,
                80,
                88,
                86,
                79,
                84,
                81,
                87,
                85,
                83,
                92,
                90,
                88,
                89,
                86,
                85,
                83,
                91,
                88,
                79,
                87,
                90,
                84,
                82,
                76,
                85,
                89,
                86,
                80,
                82,
                91,
                84,
                85,
                78,
                82,
                87,
                86,
                90,
                83,
                85,
                92,
                88,
                84,
                80,
                86,
                79,
                88,
                91,
                85,
                87,
                82,
                89,
                84,
                81,
                90,
                83,
                92,
                88,
                86,
                87,
                91,
                82,
                80,
                89,
                84,
                85,
                88,
                86,
                79
            ],
            "revisions": null
        },
        "other_images": {
            "property_name": "Two Story House w/ Balcony and Patio on the Beach",
            "rating_number": 85,
            "rating_category": "excellent",
            "feedback": {
                "summary": "Your listing's images wonderfully capture the unique beachfront experience your property offers.",
                "items": [
                    {
                        "title": "Vibrant and Inviting",
                        "feedback": "The images do a fantastic job at showcasing the vibrant and inviting nature of the beach house. You can really see how spacious and well-lit the house is, making it very appealing."
                    },
                    {
                        "title": "Outdoor Living Spaces",
                        "feedback": "The outdoor spaces, including the patio and balcony, are beautifully highlighted in the images. They clearly show the potential for relaxation and leisure, enticing potential guests."
                    },
                    {
                        "title": "Coastal Proximity",
                        "feedback": "The proximity to the water is well illustrated, emphasizing one of the strongest features of your property - the direct beach access without obstruction."
                    }
                ]
            },
            "suggestions": [
                "Include a few night-time photos of the outdoor areas to showcase ambiance.",
                "Add interior photos that give a sense of space layout for a better understanding of the property flow.",
                "Consider staging areas with cozy touches like pillows or throws for added visual warmth."
            ],
            "expert_ratings": [
                85,
                87,
                82,
                90,
                88,
                86,
                84,
                89,
                83,
                79,
                86,
                91,
                78,
                88,
                84,
                85,
                87,
                81,
                88,
                86,
                87,
                82,
                90,
                88,
                79,
                84,
                91,
                85,
                80,
                89,
                84,
                87,
                86,
                81,
                92,
                83,
                78,
                88,
                85,
                87,
                84,
                86,
                83,
                88,
                87,
                85,
                84,
                89,
                91,
                81,
                92,
                83,
                78,
                88,
                85,
                86,
                81,
                88,
                87,
                86,
                84,
                79,
                85,
                82,
                89,
                88,
                81,
                88,
                86,
                85,
                92,
                87,
                84,
                89,
                91,
                78,
                83,
                88,
                85,
                86,
                84,
                89,
                87,
                82,
                81,
                88,
                85,
                92,
                84,
                81,
                88,
                79,
                86,
                85,
                87,
                83,
                88,
                84,
                87,
                82
            ],
            "revisions": null
        },
        "interior_design": {
            "property_name": "Two Story House w/ Balcony and Patio on the Beach",
            "rating_number": 85,
            "rating_category": "excellent",
            "feedback": {
                "summary": "Your beachfront property with its cozy interior and inviting design is a delightful sanctuary for those seeking a peaceful retreat by the sea.",
                "items": [
                    {
                        "title": "Coastal Ambiance",
                        "feedback": "The interior design beautifully captures the essence of a seaside getaway with its airy spaces and beach-inspired décor. The neutral palette and natural materials enhance the calming effect."
                    },
                    {
                        "title": "Spacious and Functional Layout",
                        "feedback": "The layout of the house is both functional and family-friendly, offering ample space for relaxation and socializing. The division of bedrooms and common areas is well thought out."
                    },
                    {
                        "title": "Well-equipped Kitchen",
                        "feedback": "Guests will appreciate the fully equipped kitchen with modern appliances and beach essentials, making meal preparations and picnics on the sand a breeze."
                    }
                ]
            },
            "suggestions": [
                "Incorporate more vibrant colors or patterns in certain areas to add a touch of personality and contrast.",
                "Consider adding more local art pieces that reflect the Newport Beach culture.",
                "Upgrade the bathroom amenities for added luxury."
            ],
            "expert_ratings": [
                88,
                87,
                85,
                84,
                89,
                86,
                80,
                82,
                84,
                89,
                88,
                86,
                85,
                83,
                82,
                81,
                80,
                88,
                85,
                84,
                83,
                82,
                87,
                85,
                89,
                86,
                84,
                81,
                88,
                82,
                85,
                87,
                89,
                83,
                88,
                84,
                80,
                81,
                83,
                85,
                87,
                89,
                81,
                80,
                82,
                84,
                86,
                88,
                89,
                82,
                87,
                85,
                84,
                83,
                82,
                88,
                80,
                86,
                85,
                84,
                81,
                83,
                89,
                88,
                87,
                86,
                84,
                83,
                82,
                88,
                80,
                84,
                89,
                87,
                85,
                82,
                81,
                88,
                83,
                80,
                85,
                89,
                88,
                84,
                81,
                86,
                89,
                88,
                80,
                87,
                82,
                85,
                84,
                88,
                89,
                86,
                81,
                85,
                88,
                82
            ],
            "revisions": null
        },
        "overall_ratings": {
            "property_name": "Two Story House w/ Balcony and Patio on the Beach",
            "rating_number": 85,
            "rating_category": "excellent",
            "feedback": {
                "summary": "Your listing significantly captures the unique beachfront experience and offers ample opportunities for a comfortable stay. The visual presentation, descriptive title, and thoughtful amenities make it appealing to potential guests.",
                "items": [
                    {
                        "title": "Vibrant and Inviting",
                        "feedback": "The images do a fantastic job at showcasing the vibrant and inviting nature of the beach house. You can really see how spacious and well-lit the house is, making it very appealing."
                    },
                    {
                        "title": "Outdoor Living Spaces",
                        "feedback": "The outdoor spaces, including the patio and balcony, are beautifully highlighted in the images. They clearly show the potential for relaxation and leisure, enticing potential guests."
                    },
                    {
                        "title": "Ideal Title",
                        "feedback": "Your title clearly highlights that the property is a two-story house with a balcony and patio on the beach, which is attractive and concise."
                    }
                ]
            },
            "suggestions": [
                "Include a few night-time photos of the outdoor areas to showcase ambiance.",
                "Enhance the color contrast in photos to make them more vibrant and eye-catching.",
                "Consider staging areas with cozy touches like pillows or throws for added visual warmth."
            ],
            "expert_ratings": [
                85,
                87,
                82,
                90,
                88,
                86,
                84,
                89,
                83,
                79,
                86,
                91,
                78,
                88,
                84,
                85,
                87,
                81,
                88,
                86,
                87,
                82,
                90,
                88,
                79,
                84,
                91,
                85,
                80,
                89,
                84,
                87,
                86,
                81,
                92,
                83,
                78,
                88,
                85,
                87,
                84,
                86,
                83,
                88,
                87,
                85,
                84,
                89,
                91,
                81,
                92,
                83,
                78,
                88,
                85,
                86,
                81,
                88,
                87,
                86,
                84,
                79,
                85,
                82,
                89,
                88,
                81,
                88,
                86,
                85,
                92,
                87,
                84,
                89,
                91,
                78,
                83,
                88,
                85,
                86,
                84,
                89,
                87,
                82,
                81,
                88,
                85,
                92,
                84,
                81,
                88,
                79,
                86,
                85,
                87,
                83,
                88,
                84,
                87,
                82
            ],
            "revisions": null
        }
    }
}