-- Create market_spy_runs table for tracking end-to-end market spy operation timing
CREATE TABLE market_spy_runs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- User and request info
    profile_id UUID REFERENCES profiles(id),
    scan_id VARCHAR(255), -- Links to scan from Node backend
    address TEXT,
    geocode TEXT, -- lat,lng coordinates
    
    -- Timing data
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE, 
    execution_time_ms INTEGER,
    
    -- Breakdown timing
    scraping_time_ms INTEGER, -- Time spent scraping Airbnb
    assessment_time_ms INTEGER, -- Time spent on FastAPI property assessments
    
    -- Results metadata
    target_listings INTEGER, -- TARGET_LISTINGS env var value
    listings_found INTEGER, -- How many listings were scraped
    listings_assessed INTEGER, -- How many got property assessments
    
    -- Status tracking
    status VARCHAR(50) DEFAULT 'in_progress', -- in_progress, completed, failed
    error_message TEXT -- If failed, what went wrong
);

-- Create indexes for performance
CREATE INDEX idx_market_spy_runs_profile_id ON market_spy_runs(profile_id);
CREATE INDEX idx_market_spy_runs_scan_id ON market_spy_runs(scan_id);
CREATE INDEX idx_market_spy_runs_started_at ON market_spy_runs(started_at);
CREATE INDEX idx_market_spy_runs_execution_time ON market_spy_runs(execution_time_ms);

-- Add RLS policy
ALTER TABLE market_spy_runs ENABLE ROW LEVEL SECURITY;

-- Policy: Users can only see their own market spy runs
CREATE POLICY "Users can view own market spy runs" ON market_spy_runs
    FOR SELECT USING (auth.uid() = profile_id);

-- Policy: Users can insert their own market spy runs  
CREATE POLICY "Users can insert own market spy runs" ON market_spy_runs
    FOR INSERT WITH CHECK (auth.uid() = profile_id);

-- Policy: Users can update their own market spy runs
CREATE POLICY "Users can update own market spy runs" ON market_spy_runs
    FOR UPDATE USING (auth.uid() = profile_id);

-- Add comments for documentation
COMMENT ON TABLE market_spy_runs IS 'Tracks timing and metadata for end-to-end market spy operations';
COMMENT ON COLUMN market_spy_runs.execution_time_ms IS 'Total time from address input to final results in milliseconds';
COMMENT ON COLUMN market_spy_runs.scraping_time_ms IS 'Time spent scraping Airbnb listings in milliseconds';
COMMENT ON COLUMN market_spy_runs.assessment_time_ms IS 'Time spent on FastAPI property assessments in milliseconds';
COMMENT ON COLUMN market_spy_runs.scan_id IS 'Links to the scan ID generated by Node backend for this operation';